apiVersion: v1
kind: ConfigMap
metadata:
  name: collectorset-controller
data:
  config.yaml: |
    debug: {{ required "A valid .Values.debug entry is required!" .Values.debug }}
    {{- if .Values.proxyURL }}
    proxy_url: {{ .Values.proxyURL }}
    {{- end }}
  jaeger-config.yaml: |
{{- with .Values.jaegerconf }}
{{ toYaml . | indent 4 }}
{{- end }}
