imageRepository: logicmonitor/argus
imageTag: v4
imagePullPolicy: Always
disableAlerting: false
deleteDevices: true
debug: false
enableRBAC: true
clusterName: ""
accessID: ""
accessKey: ""
account: ""
etcdDiscoveryToken: ""
proxyUser: ""
proxyPass: ""
proxyURL: ""
clusterGroupID: 0
nodeSelector: {}
affinity: {}
priorityClassName: ""
tolerations: []
filters:
  pod: ""
  service: ""
  node: ""
  deployment: ""
collector:
  imageRepository: logicmonitor/collector
  imageTag: latest
  imagePullPolicy: Always
  secretName: collector
  replicas: 1
  size: ""
  groupID: 0
  escalationChainID: 0
  collectorVersion: 0
  useEA: false
  proxyURL: ""
  proxyUser: ""
  proxyPass: ""
  priorityClassName: ""
  tolerations: []
jaegerconf:
  serviceName: argus
  disabled: false
  rpc_metrics: false
  tags:
    - tagkey: tagvalue
  sampler:
    type: const
    param: 1
    samplingServerURL: ""
    samplingRefreshInterval: "1m"
    maxOperations: 1000
    operationNameLateBinding: false
  reporter:
    queueSize: 100
    logSpans: false
    localAgentHostPort: ""
    disableAttemptReconnecting: false
    collectorEndpoint: ""
    user: ""
    password: ""
    http_headers:
      User-Agent: "Argus-Jaeger"
  headers:
    jaegerDebugHeader: ""
    jaegerBaggageHeader: ""
    TraceContextHeaderName: ""
    traceBaggageHeaderPrefix: ""
  baggage_restrictions:
    denyBaggageOnInitializationFailure: false
    hostPort: ""
    refreshInterval: "10s"
  throttler:
    hostPort: ""
    refreshInterval: "1m"
    synchronousInitialization: false
